version: '3'
services:
  db:
    image: mysql:8
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: my-mysql
    ports:
      - 8080:80
