version: '3'
services:
  my-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-server
    links:
      - my-mysql
    depends_on:
      - my-mysql
    ports:
      - "5000:5000"
    volumes:
      - ./server.js:/usr/server.js
  my-mysql:
    image: mysql:8
    container_name: "my-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "mydatabase"
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - my-mysql
    environment:
      PMA_HOST: my-mysql
    ports:
      - 8080:80
